// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CenterWindow(arg1, arg2) {
  return window['go']['main']['App']['CenterWindow'](arg1, arg2);
}

export function CodexUsage(arg1, arg2) {
  return window['go']['main']['App']['CodexUsage'](arg1, arg2);
}

export function Details(arg1) {
  return window['go']['main']['App']['Details'](arg1);
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function FinishHide(arg1) {
  return window['go']['main']['App']['FinishHide'](arg1);
}

export function FrontendReady() {
  return window['go']['main']['App']['FrontendReady']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function Hide() {
  return window['go']['main']['App']['Hide']();
}

export function Icon(arg1) {
  return window['go']['main']['App']['Icon'](arg1);
}

export function OpenConfig() {
  return window['go']['main']['App']['OpenConfig']();
}

export function PresentationReady(arg1) {
  return window['go']['main']['App']['PresentationReady'](arg1);
}

export function ProcessMonitor() {
  return window['go']['main']['App']['ProcessMonitor']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Reindex() {
  return window['go']['main']['App']['Reindex']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function ReportFocus(arg1, arg2) {
  return window['go']['main']['App']['ReportFocus'](arg1, arg2);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['main']['App']['Search'](arg1, arg2, arg3);
}

export function Sensors() {
  return window['go']['main']['App']['Sensors']();
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
