// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {codexusage} from '../models';
import {launcher} from '../models';
import {main} from '../models';
import {sensors} from '../models';

export function CenterWindow(arg1:number,arg2:number):Promise<void>;

export function CodexUsage(arg1:string,arg2:boolean):Promise<codexusage.Snapshot>;

export function Details(arg1:string):Promise<launcher.Details>;

export function Execute(arg1:string):Promise<void>;

export function FinishHide(arg1:number):Promise<void>;

export function FrontendReady():Promise<void>;

export function GetState():Promise<main.AppState>;

export function Hide():Promise<void>;

export function Icon(arg1:string):Promise<string>;

export function OpenConfig():Promise<void>;

export function PresentationReady(arg1:number):Promise<void>;

export function Quit():Promise<void>;

export function Reindex():Promise<void>;

export function ReloadConfig():Promise<void>;

export function ReportFocus(arg1:boolean,arg2:boolean):Promise<void>;

export function Search(arg1:string,arg2:string,arg3:number):Promise<launcher.Response>;

export function Sensors():Promise<sensors.Snapshot>;

export function SetTheme(arg1:string):Promise<void>;
